### ISSUE TITLE
supprt for Llama3-8b

### ISSUE THREAD

**Issue by shiyuetianqiang** [thu-nics/MoA#3]
Hi，thanks for your great job
I have tried to follow your job in Llama3-8B
It is smooth in step "Calibration Dataset Generation"
As for the step "Profile"
It is OK for 2k and 4k, but for the 8k case, it rasied the error
"Total number of data samples: 0
Collecting Grad: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "MoA/scripts/pipeline/pipeline_profile.py", line 244, in <module>
    grad_W_dict, grad_Attn_tensor = Grad_Collect(model, tokenizer, args, dataset, args.max_length, user_prefix=user_prefix, assistant_prefix=assistant_prefix)
  File "MoA/scripts/pipeline/pipeline_profile.py", line 170, in Grad_Collect
    grad_Attn_tensor = torch.sum(model.model.attention_matrix_log[key][0], dim=0) / num_data
IndexError: list index out of range
"
Do you have any suggestions ?

And could you change the gurobi to other opensource lib?

**Comment by fuvty** [comment]
Hi @shiyuetianqiang , thank you for your interest in our work. The problem seems to be the empty dataset passed to Grad_Collect: `Total number of data samples: 0`. Can you check why the dataset is empty? 
If it is not empty before filtering (suggesting successful Calibration Dataset Generation), I think the main problem may come from tokenization: Llama3 tokenizer is more efficient than Llama2. Yet, the lengths of our data items on HuggingFace are calculated with Llama2 tokenizer. As a result, the data items do not reach 7-8k as expected by "Profile". 

To fix this, we provide two optional solutions:
1. We add a re-calculation of lengths in "Calibration Dataset Generation" based on the current tokenizer. Please check our latest commit. Rerun "Calibration Dataset Generation" to see if the longest length reaches 8k
2. Set a smaller "--max_length" (e.g., 6k) or larger "--total_length_level_down" during "Profile"

Please let us know if the problem still exists. Welcome to open PRs if you come up with better solutions.

**Comment by fuvty** [comment]
As for gurobi, you can apply free academic license for in class or research uses [here](https://www.gurobi.com/academia/academic-program-and-licenses/)

**Comment by shiyuetianqiang** [comment]
> As for gurobi, you can apply free academic license for in class or research uses [here](https://www.gurobi.com/academia/academic-program-and-licenses/)

Thanks，for gurobi， we have applied a 30-day trail license

**Comment by shiyuetianqiang** [comment]
> Hi @shiyuetianqiang , thank you for your interest in our work. The problem seems to be the empty dataset passed to Grad_Collect: `Total number of data samples: 0`. Can you check why the dataset is empty? If it is not empty before filtering (suggesting successful Calibration Dataset Generation), I think the main problem may come from tokenization: Llama3 tokenizer is more efficient than Llama2. Yet, the lengths of our data items on HuggingFace are calculated with Llama2 tokenizer. As a result, the data items do not reach 7-8k as expected by "Profile".
> 
> To fix this, we provide two optional solutions:
> 
> 1. We add a re-calculation of lengths in "Calibration Dataset Generation" based on the current tokenizer. Please check our latest commit. Rerun "Calibration Dataset Generation" to see if the longest length reaches 8k
> 2. Set a smaller "--max_length" (e.g., 6k) or larger "--total_length_level_down" during "Profile"
> 
> Please let us know if the problem still exists. Welcome to open PRs if you come up with better solutions.

Yes, you r right,
When come back to the step of "Calibration Dataset Generation" by Llama3 tokenizer， the max sequence length is no no longer than 8k.
Follow your suggestion, we set a smaller "--max_length"
